### 라이브러리 로드
- ipmort 라이브러리명 as 별칭
- from 라이브러리명 import 라이브러리 안 특정 기능

In [64]:
import pandas as pd

In [7]:
# 1차원 데이터형인 Series 생성
series_1 = pd.Series(
    [5000, 6000, 6500, 6500]
)

In [8]:
series_1

0    5000
1    6000
2    6500
3    6500
dtype: int64

In [9]:
series_2 = pd.Series(
    ['A', 'B', 'C']
)

In [10]:
series_2

0    A
1    B
2    C
dtype: object

In [16]:
series_3 = pd.Series(
    ['A', 10, True]
)

In [17]:
series_3

0       A
1      10
2    True
dtype: object

In [20]:
type(series_3[1])

int

In [21]:
# Seires 라는 class에는 적어도 2개의 변수가 존재
# 값들이 저장되어있는 values
# values의 키값인 index
print("Series에서 values는 ", series_1.values)
print("Series에서 index는 ", series_1.index)

Series에서 values는  [5000 6000 6500 6500]
Series에서 index는  RangeIndex(start=0, stop=4, step=1)

In [22]:
series_1[1]

np.int64(6000)

In [24]:
series_1[1] = 5500

In [26]:
series_1[1]

np.int64(5500)

In [27]:
series_1

0    5000
1    5500
2    6500
3    6500
dtype: int64

In [29]:
series_1[5] = 6000

In [31]:
series_1

0    5000
1    5500
2    6500
3    6500
5    6000
dtype: int64

In [32]:
series_1.index

Index([0, 1, 2, 3, 5], dtype='int64')

In [33]:
# index 값을 변경한다 --> 
# Series class 내부에 존재하는 index 변수의 데이터를 다른값으로 채워준다.
series_1.index

Index([0, 1, 2, 3, 5], dtype='int64')

In [35]:
# serire 안에 index를 변경하는데 values의 길이와 맞지 않는 경우
# series_1.index = [0,1,2,3,4,5]
# 길이가 맞지 않는다면 에러 발생

In [38]:
# 특정 인덱스만 변경하려고 한다.
# series_1.index[2] = 10

In [40]:
_values = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

_index = ['a','b','c']
_cols = ['A','B','C']

df = pd.DataFrame(_values, index = _index, columns=_cols)

In [43]:
df

   A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [50]:
# rename() 함수를 이용해서 특정 인덱스나 특정 컬럼을 수정
# df 의 컬럼 중 B 컬럼의 이름을 F 로 변경
# inplace 매개변수를 True 변경하면 df의 데이터가 변경되고 출력 x
df.rename(
    columns= {
        'B' : 'F'
    },
    inplace=True
)

In [51]:
df2 = df.copy()

In [52]:
df2

   A  F  C
a  1  2  3
b  4  5  6
c  7  8  9

In [58]:
df2 = df2.rename(
    columns={
        'C' : 'A'
    }, inplace=True
)

AttributeError: 'NoneType' object has no attribute 'rename'

In [60]:
df2
# inplace가 True 이면 return으로 되돌려주는 데이터가 존재하지 않는다.
# df2 = None 들어가는 형태로 df2의 데이터를 모두 제거

In [61]:
# DataFrame 안에 있는 columns 변수의 데이터를 변경
df.columns = ['name','age','loc']

In [62]:
df

   name  age  loc
a     1    2    3
b     4    5    6
c     7    8    9

#### pandas 라이브러리를 이용하여 외부의 데이터파일 로드
- csv, tsv
    - 가장 단순한 형태 데이터 파일
    - pandas 안에 내장된 read_csv() 함수를 이용하여 로드
    - csv는 데이터를 ','를 기준으로 나눠준다.
        - read_csv()를 기본값으로 사용
    - tsv는 데이터를 '\t' 기준으로 나눠준다
        - read_csv() 함수에서 sep 매개변수에 인자값을 '\t' 대입
- json
    - 많이 사용하는 데이터의 파일
    - python을 기준으로 생각하면 dict 형태와 같다
    - pandas 안에 read_json() 함수를 이용하여 로드
- xml
    - html 구조 언어와 같이 tag를 이용하여 데이터 구성
    - pandas 안에 read_xml() 함수를 이용하여 로드
- 공통적으로 사용되는 매개변수
    - encoding 매개변수
        - 기본값은 'UTF-8'
        - 데이터 파일을 로드 하는데 해당 데이터에 한글이 존재할 때
        종종 에러가 발생
            - 'CP949', 'EUC-KR' 로 매개변수에 대입 -> 에러 해결
        - 엑셀 파일을 로드하는 학술에서는 encoding 매개변수가 존재하지 않는다.
- excel( xls, xlsx )
    - 엑셀 데이터 파일 
    - pandas 안에 read_excel() 함수를 이용
    - 특정 엑셀 파일을 로드 할때는 추가적인 라이브러리 설치가 필요한 경우가 발생
        - 해당 라이브러리가 설치가 되지 않은 경우에는 에러 발생
        (모듈을 찾을 수 없다.)
        - openpyxl 라이브러리를 설치하면 에러 해결
- read_xxx() 공통적인 부분
    - 첫번째 인자 : 파일의 경로

#### 경로 
- 절대 경로
    - 절대적인 주소값
    - 환경이 변하더라도 같은 위치를 언제나 지정 
    - ex)
        - window -> c:/users/admin/document/a.txt
        - mac -> ~/Desktop/a.txt
        - URL -> https://www.google.com
- 상대 경로
    - 상대적인 주소값
    - 환경이 변할때 위치도 같이 변한다
    - 종류
        - ./ -> 현재 작업중인 디렉토리
        - ../ -> 상위(부모) 디렉토리로 이동
        - 디렉토리명/ -> 하위(자식) 디렉토리 이동

In [67]:
# 외부의 데이터파일 로드
# 절대 경로 사용
df = pd.read_csv(
    r"C:\Users\johnh\python file\csv\example.csv"
)
# r스트링 기법 : r 아래에 텍스트가 경로를 나타낸다는것을 알려주는 기법

In [69]:
df

  Name  Gender          Phone
0    A    male  010-1234-5678
1    B  female  010-1234-5679
2    C    male  010-1234-5680
3    D  female  010-1234-5681
4    E    male  010-1234-5682
5    F  female  010-1234-5683
6    G    male  010-1234-5684
7    H  female  010-1234-5685
8    I    male  010-1234-5686
9    J  female  010-1234-5687

In [74]:
# 상대 경로 이용
# 현재 디렉토리(./)->상위 디렉토리 이동(../)->csv 하위 디렉토리 이동(csv/)
# -> example.csv
df2 = pd.read_csv(
    "./../csv/example.csv"
)

In [71]:
df2

  Name  Gender          Phone
0    A    male  010-1234-5678
1    B  female  010-1234-5679
2    C    male  010-1234-5680
3    D  female  010-1234-5681
4    E    male  010-1234-5682
5    F  female  010-1234-5683
6    G    male  010-1234-5684
7    H  female  010-1234-5685
8    I    male  010-1234-5686
9    J  female  010-1234-5687

In [75]:
# tsv 파일 로드
# read_csv() 함수를 이용
# 상대 경로
# 현재 경로(./)->상위 디렉토리로 이동(../) -> 하위 csv디렉토리로 이동 (csv/) -> 하위 num_1 디렉토리로 이동(num_1/) -> 
# chipotle.tsv
df3 = pd.read_csv(
    "./../csv/num_1/chipotle.tsv", sep = '\t'
)

In [76]:
df3

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [77]:
# csv 폴더 안에 있는 2021 폴더에서 json 데이터 로드
# read_json() 함수 이용
# 현재 경로(./) -> 상위 디렉토리로 이동(../) -> 하위 csv 디렉토리 이동(csv/)
# -> 하위 2021 디렉토리 이동 -> 202101_xxxxx.json

df4 = pd.read_json(
    "./../csv/2021/202101_expense_list.json"
)

In [79]:
df4.head(1)

,nid,title,url,dept_nm_lvl_1,dept_nm_lvl_2,dept_nm_lvl_3,dept_nm_lvl_4,dept_nm_lvl_5,exec_yr,exec_month,...,expense_execution,category,dept_nm_full,exec_dt,exec_loc,exec_purpose,target_nm,payment_method,exec_amount,bimok
0,22249566,2021년 1월 사업소 물재생센터 중랑물재생센터 업무추진비 - 전체,http://opengov.seoul.go.kr/public/22249566,사업소,물재생센터,중랑물재생센터,,,2021,1,...,NaN,,중랑물재생센터 관리과,2021-01-25 00:00,,소속직원 경조사비,"김광옥, 김용성",현금,100000,None

In [82]:
# 같은 경로에 있는 xml 파일을 로드
df5 = pd.read_xml(
    "./../csv/2021/202101_expense_list.xml"
)

In [ ]:
# !pip install lxml

Collecting lxml
  Obtaining dependency information for lxml from https://files.pythonhosted.org/packages/b1/08/28440437521f265eff4413eb2a65efac269c4c7db5fd8449b586e75d8de2/lxml-6.0.1-cp311-cp311-win_amd64.whl.metadata
  Downloading lxml-6.0.1-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Downloading lxml-6.0.1-cp311-cp311-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB 660.6 kB/s eta 0:00:07
   -- ------------------------------------- 0.3/4.0 MB 3.5 MB/s eta 0:00:02
   -------- ------------------------------- 0.9/4.0 MB 6.9 MB/s eta 0:00:01
   ---------------- ----------------------- 1.6/4.0 MB 9.3 MB/s eta 0:00:01
   ------------------------- -------------- 2.6/4.0 MB 11.7 MB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 13.2 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 12.9 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.1

[notice] A new release of pip is available: 23.2.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [84]:
df5.head(1)

,nid,title,url,dept_nm_lvl_1,dept_nm_lvl_2,dept_nm_lvl_3,dept_nm_lvl_4,dept_nm_lvl_5,exec_yr,exec_month,...,expense_execution,category,dept_nm_full,exec_dt,exec_loc,exec_purpose,target_nm,payment_method,exec_amount,bimok
0,22249566,2021년 1월 사업소 물재생센터 중랑물재생센터 업무추진비 - 전체,http://opengov.seoul.go.kr/public/22249566,사업소,물재생센터,중랑물재생센터,None,None,2021,1,...,NaN,None,중랑물재생센터 관리과,2021-01-25 00:00,None,소속직원 경조사비,"김광옥, 김용성",현금,100000,None

In [87]:
# 같은 경로에 있는 엑셀 파일을 로드
df6 = pd.read_excel(
    "./../csv/2021/202101_expense_list.xlsx"
)

In [ ]:
# !pip install openpyxl

Collecting openpyxl
  Obtaining dependency information for openpyxl from https://files.pythonhosted.org/packages/c0/da/977ded879c29cbd04de313843e76868e6e13408a94ed6b987245dc7c8506/openpyxl-3.1.5-py2.py3-none-any.whl.metadata
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Obtaining dependency information for et-xmlfile from https://files.pythonhosted.org/packages/c1/8b/5fe2cc11fee489817272089c4203e679c63b570a5aaeb18d852ae3cbba6a/et_xmlfile-2.0.0-py3-none-any.whl.metadata
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
   ---------------------- ----------------- 143.4/250.9 kB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 3.8 MB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 23.2.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [89]:
df6.head(2)

,nid,title,url,dept_nm_lvl_1,dept_nm_lvl_2,dept_nm_lvl_3,dept_nm_lvl_4,dept_nm_lvl_5,exec_yr,exec_month,...,expense_execution,category,dept_nm_full,exec_dt,exec_loc,exec_purpose,target_nm,payment_method,exec_amount,bimok
0,22249566,2021년 1월 사업소 물재생센터 중랑물재생센터 업무추진비 - 전체,http://opengov.seoul.go.kr/public/22249566,사업소,물재생센터,중랑물재생센터,NaN,NaN,2021,1,...,NaN,NaN,중랑물재생센터 관리과,2021-01-25 00:00,NaN,소속직원 경조사비,"김광옥, 김용성",현금,100000,NaN
1,22249566,2021년 1월 사업소 물재생센터 중랑물재생센터 업무추진비 - 전체,http://opengov.seoul.go.kr/public/22249566,사업소,물재생센터,중랑물재생센터,NaN,NaN,2021,1,...,NaN,NaN,중랑물재생센터 운영과,2021-01-22 00:00,복시루,운영과 다과구매-전출직원선물,NaN,카드,90000,NaN

In [91]:
# data 파일에서 한글때문에 에러가 발생하는 경우
# csv 폴더 안에 '주민등록.csv' 파일을 로드
# 현재 경로("./") -> 상위 디렉토리("../") -> 하위 csv 디렉토리 이동(csv/) -> 주민등록 csv파일 선택(주민등록.csv)
df7 = pd.read_csv(
    "./../csv/주민등록.csv", encoding="CP949"
)

In [92]:
df7.head()

,자치구코드(atdrc_code_se),자치구명(atdrc_nm),년월(년월),총인구수(tot_popltn_co),세대수(tot_hshld_co),세대당인구(hshld_popltn_avrg_co),남자인구수(male_popltn_co),여자인구수(female_popltn_co),적재일시(ldadng_dt)
0,금천구,11110,201907,228755,171426,2.44,319062,118352,2018-01-05 16:52:25
1,서대문구,11290,201607,153780,186744,2.12,75614,116393,2018-12-05 10:20:57
2,양천구,11740,201804,594315,61091,2.22,192817,307237,2020-11-03 10:50:11
3,은평구,11200,202004,345156,168865,2.13,229690,204108,2018-01-05 16:52:25
4,마포구,11260,201902,394788,168482,2.52,61714,146951,2018-01-05 16:52:25

#### 결측치
- 데이터프레임에서 특정 부분에 데이터가 존재하지 않는 경우
- NaN 표시